pipeline {
    agent any
    environment {
        MVN_HOME = '/usr/share/maven' // Replace with actual path
    }
    stages {
        stage ('Preparation'){
            steps {
                git 'https://github.com/thiago-jv/VOTACAO_API.git' // Assuming Maven is in PATH
            }
        }
        stage ('Build Backend'){
            steps {
                sh 'mvn clean package'
            }
        }
    }
}