pipeline {
    agent any
    environment {
            MAVEN_HOME = '/usr/share/maven'
    stages {
        stage ('Build Backend'){
            steps {
                try {
                   sh "${MAVEN_HOME}/bin/mvn clean package -DskipTests"
                } catch (Exception e) {
                   error "Build failed: ${e.message}"
               }
            }
        }
    }
}