pipeline {
    agent any
    environment {
        MVN_HOME = '/usr/share/maven' // Replace with actual path
    }
    stages {
        stage ('Preparation'){
            steps {
                git branch: 'main', credentialsId: 'GIT', url: 'https://github.com/thiago-jv/VOTACAO_API.git'
                dir('votacao') {
                sh 'mvn clean package'
               }
            }
        }
    }
}